```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```
# Data
## Technical description
Below are the two datasets that we propose to draw on for the project:   
1. [Mental Health - Depression Screener](https://wwwn.cdc.gov/Nchs/Nhanes/Search/DataPage.aspx?Component=Questionnaire&Cycle=2017-2018)    
2. [Dietary Interview - Individual Foods, First Day](https://wwwn.cdc.gov/Nchs/Nhanes/Search/DataPage.aspx?Component=Dietary&Cycle=2017-2018)    

Both of those datasets are downloaded from CDC National Health and Nutrition Examination Survey. The survey examines a nationally representative sample of about 6,000 people each year. The NHANES interview includes demographic, socioeconomic, dietary, and health-related questions.  

This project was to examine the dataset from 2017 to 2018. There were 7,640 participants who provided reliable responses to inquiries about caffeine consumption, and 5,533 participants who answered questions regarding depression. Participants’ depression levels were assessed using the 9-item Patient Health Questionnaire depression scale. For each symptom question, points are scored from 0 to 3, with 0 (not at all), 1 (several days), 2 (more than half the days), and 3 (nearly every day). The caffeine intake was collected in-person in the Mobile Examination Center of NHANES. Participants were asked to provide detailed dietary intake information during the 24-hr period prior to the interview. NHANES then calculated the energy and 64 nutrients (including caffeine) of each food using the USDA’s Food and Nutrient Database for Dietary Studies, and estimated participants’ caffeine intake.  

Since the data are in the XPT (SAS file) format, we can use the haven package and the command `read_xpt` to import the data. In NHANES data, each sample person has a unique identifier called sequence number (SEQN). The next step is to merge two datasets by a unique identifier. However, the data file `Dietary Interview - Individual Foods` contains multiple records for each sample person and makes them not a unique identifier. Also, the number of participants who took the survey for caffeine consumption is more than depression. When we merge data, this will cause the problem of missing data. The way to solve these issues will be described in the `Research plan` section.  

## Research plan
The plan is divided into three parts: merging datasets, processing data, and using exploratory techniques to answer research questions.  

### Merge Datasets
As the issue we mentioned in the above section, this problem is due to the investigation including the time of eating occasion for each person of the whole day ranging from 00:00 to 23:59. Since we only need to analyze caffeine, we can solve it by only keeping SEQN and caffeine intake columns for the Dietary dataset. Then, we can group the SEQN and sum up the caffeine intake of each participant from all time slots for the whole day. Now, we can merge two datasets together by SEQN.  

### Process Data
For the Depression part of the merged dataset, patients will be asked nine questions and they will score them from 0 to 3. In addition to those 4 scores, participants who wrote down 7 means that they refused to answer and 9 means that they don’t know. For these cases, we just treat them as 0. Since participants are actually being asked 10 questions, the last question in the survey does not relate to depression symptoms over the past 2 weeks, and so we decided to delete that column. In order to analyze the depression level more easily, the scores are summed to a total score between 0 and 27. By doing this, we can now see the relationship between caffeine intake and depression level more clearly. Also, since the number of participants who took the survey for caffeine consumption is more than depression, there will be missing values in the merged dataset. We shall delete these data by using the command `na.omit()`. After processing the data, there are 3169 participants left who took both dietary interviews and depression surveys.  

### Use Exploratory Techniques


## Missing value analysis

